### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by cneud** [OCR-D/gt-guidelines#14]
https://ocr-d.github.io/gt//trans_documentation/trSchreibungR.html

**Comment by cneud** [comment]
https://github.com/OCR-D/gt-guidelines/blob/master/trans_documentation/tr_level_2_3.dita#L23

**Comment by cneud** [comment]
https://github.com/OCR-D/gt-guidelines/blob/master/trans_documentation/lyRand.dita#L9

**Comment by cneud** [comment]
https://github.com/OCR-D/gt-guidelines/blob/master/trans_documentation/structur_gtpageformat.dita#L9

**Comment by cneud** [comment]
https://github.com/OCR-D/gt-guidelines/blob/master/trans_documentation/structurmets2page.dita#L8

**Comment by EEngl52** [comment]
those are a few of the sentences or paragraphes which I was unsure how to translate. Therefore I left the comments for @tboenig . They are also tracked in the ToDo file.

**Comment by cneud** [comment]
@EEngl52 @tboenig Looks to me you already fixed all of the above, so closing this.
