### ISSUE TITLE
show example images of font families

### ISSUE THREAD

**Issue by bertsky** [OCR-D/gt-guidelines#21]
In `trans/lySchriftarten`, the major historically adequate fontFamily clusters are listed that have been identified by the Leipzig/Erlangen-Nürnberg/Mainz module project:
> - textura
> - rotura
> - bastarda
> - antiqua
> - greek
> - hebrew
> - italic
> - fraktur

It would be great if an example for each could be added to the page, like figure 3 from http://digitalia.sbn.it/article/view/2630/1837.

**Comment by tboenig** [comment]
see branch: DITA-OT-OCRD_NewFeature, at first only german language
