### ISSUE TITLE
Why all the content on Google

### ISSUE THREAD

**Issue by kba** [OCR-D/gt-guidelines#4]
E.g. https://lh4.googleusercontent.com/1HdqrPTGjE0nHay-YhnX16ipvQzmWW44oiWjsL4x9lh-aRq_J-flmV1oNOgflJFu5T-F9OEvKeQW8H1i_7gR7EMcF36wq1E8ktKO2fBWqLw2NDylG81YNE-Yt6DK8P599sZXajvP and many more.

**Comment by tboenig** [comment]
There is a workflow error in the creation of the DITA files. The images for the PAGE documentation are stored in the `img` directory and the images for the documentation, for example for the description of the transcription, are stored in the `images` directory.

**Comment by kba** [comment]
OK, can we clean this up? Maybe a hierarchy like

```
/
/images
/images/pagexml   <- generated images
/images/figures   <- snippets of glyphs and layout specimen etc.
/images/layout    <- Stuff like arrows, plus/minus buttons, borders etc. used for UI
/dita/pagexml       <- generated DITA about PAGE XML (?)
/dita/gt-guidelines <- The actual prose
/dita/gt-guidelines/en
/dita/gt-guidelines/de
/build              <- output and temp files, to be .gitignored
```

**Comment by kba** [comment]
obsolete
