### ISSUE TITLE
Branch pruned of all generated/temporary output

### ISSUE THREAD

**Issue by kba** [OCR-D/gt-guidelines#7]
Branch https://github.com/OCR-D/gt-guidelines/tree/purged is a rewrite of the git history, undoing all commits to

* documentation/out
* documentation/temp
* page_documentation/out
* documentation/img/pagecontent*

which reduces the size of repo and index by about 400 MB.

Since this is changes the git history, it cannot be merged, we need to rebase master on it (hence no PR hence this issue).

**Comment by kba** [comment]
@tboenig I will update this once you give the okay.

**Comment by tboenig** [comment]
It's okay.
